// Single re-export point for Phosphor icons used across the app.
// Every glyph defaults to the "light" weight to match the design reference
// (`docs/design-reference/pitchai-analyst.html`, ph-light).
export {
  CaretDown,
  CaretUp,
  SidebarSimple,
  UserPlus,
  Trophy,
  SoccerBall,
  MagnifyingGlass,
  Hourglass,
  ArrowLineRight,
  UploadSimple,
  SignOut,
  Question,
  PaperPlaneRight,
  Globe,
  Gear,
  ClockCounterClockwise,
  Check,
  ChartLineUp,
  ChartLine,
  Books,
  X,
  ArrowsClockwise,
  Trash,
  Eye,
  EyeSlash,
  WifiSlash,
  CheckCircle,
  WarningCircle,
  Circle,
} from "@phosphor-icons/react";
