import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        // Prototype's fuller semantic palette (docs/design-reference/pitchai-analyst.html
        // inline Tailwind config), ported verbatim as literal hexes so component markup
        // can use these classes near-verbatim. Coexists with the var(--…) tokens above.
        "card-surface": "#18181b",
        "on-error-container": "#ffdad6",
        "surface-tint": "#b9cf6a",
        surface: "#0a0a0b",
        "inverse-on-surface": "#1f1f22",
        "on-primary-container": "#14210a",
        "on-secondary": "#14210a",
        "on-error": "#450a0a",
        "surface-variant": "#232326",
        "surface-container-lowest": "#050506",
        "on-tertiary": "#3a1020",
        "on-primary-fixed-variant": "#2b3a16",
        "on-tertiary-fixed-variant": "#4a1a2c",
        "secondary-container": "#3a4a22",
        "inverse-surface": "#e9e8e3",
        "error-container": "#5c0d0d",
        tertiary: "#e7a8bd",
        "surface-container-low": "#111113",
        "outline-variant": "#303033",
        "accent-dim": "#4a5a34",
        "on-secondary-fixed": "#14210a",
        outline: "#8a8a86",
        "on-surface-variant": "#a3a39e",
        "primary-fixed": "#c7d98d",
        "on-secondary-fixed-variant": "#2b3a16",
        "on-background": "#e9e8e3",
        "on-primary": "#14210a",
        "surface-container-high": "#1f1f22",
        "surface-container-highest": "#28282b",
        "secondary-fixed": "#d3e2a0",
        "tertiary-fixed": "#f6d3de",
        "on-tertiary-fixed": "#3a1020",
        "on-surface": "#e9e8e3",
        "off-white": "#f2f1ec",
        "surface-sunken": "#0d0d0e",
        "on-primary-fixed": "#14210a",
        "tertiary-fixed-dim": "#f0aac0",
        "on-tertiary-container": "#4a1a2c",
        "tertiary-container": "#7a3a4f",
        "surface-bright": "#2b2b2e",
        "primary-fixed-dim": "#b9cf6a",
        "primary-container": "#b9cf6a",
        "surface-dim": "#0a0a0b",
        error: "#ff9a90",
        "secondary-fixed-dim": "#a8c46a",
        "surface-container": "#141416",
        "on-secondary-container": "#d3e2a0",
        "inverse-primary": "#5a6e2c",
      },
      borderRadius: {
        DEFAULT: "3px",
        sm: "2px",
        md: "3px",
        lg: "3px",
        xl: "4px",
        "2xl": "4px",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "280px",
        gutter: "1rem",
        "container-margin": "1.5rem",
        unit: "0.25rem",
      },
      fontFamily: {
        sans: ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        serif: ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        mono: ["var(--font-source-code)", "Source Code Pro", "monospace"],
        "headline-xl": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-lg-mobile": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "headline-xl-mobile": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-sm": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-md": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "body-lg": ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        "label-md": ["var(--font-source-code)", "Source Code Pro", "monospace"],
        "label-sm": ["var(--font-source-code)", "Source Code Pro", "monospace"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "0em", fontWeight: "800" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "0em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl-mobile": ["32px", { lineHeight: "38px", letterSpacing: "0em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "700" }],
      },
      letterSpacing: {
        theme: "var(--letter-spacing)",
      },
    },
  },
  plugins: [],
};

export default config;
